### ISSUE TITLE
Tests fail with "PagedError: missing paged control" from PR #2

### ISSUE THREAD

**Issue by jsumners** [jsumners/node-activedirectory#3]
PR #2 causes the tests to fail.

@jurjendijkstra-vma the tests are failing with the last PR you sent in. I should have checked it before I merged. I have reverted the change for now. If you get a chance to look at the issue before I do, that'd be great.

**Comment by jurjendijkstra-vma** [comment]
Indeed, you are right, I had not used the test script in the activedirectory2 module and when I do now, I see it is failing just like you said.  I am looking into it, I will start by trying to figure out how test/mockServer works and if it possibly behaves different than ldapjs version 1.0.1.

**Comment by jurjendijkstra-vma** [comment]
I think I have found it, well, at least the unittest is all green now and I can still get thousands of users.  The problem was that the mockServer did not really support paging according to the method that is invoked by setting options.paged=true.  (which is implemented in ldapjs/lib/client/search_pager). 

I am now simply ignoring the err in res.on('pageError'...)  It is probably better to do something with it, but what?

**Comment by jsumners** [comment]
Resolved by commit e77329b supporting `paged: true` and the original paging control insertion.
